/**
 * demoProfile.ts
 * Owner: Chetan
 *
 * Pre-computed enrollment constants for demo mode.
 * Derived by running fuzzyGen() with a fixed Float32[64] enrollment vector
 * representing an "average" typing pattern.
 *
 * These constants allow the demo to run biometric scoring for real on
 * actual user input, without requiring Phantom or on-chain enrollment.
 *
 * DEMO_HELPER_DATA  — pre-computed BCH syndrome (16 bytes)
 * DEMO_COMMITMENT   — pre-computed SHA256(key R) (32 bytes)
 * DEMO_CIPHERTEXT   — pre-computed AES-GCM encrypted secret (base64)
 * DEMO_VECTOR       — the enrollment vector these constants were derived from
 *
 * HOW THESE WERE GENERATED:
 *   1. Define DEMO_ENROLLMENT_VECTOR (fixed Float32[64])
 *   2. quantize() → 64-bit string w
 *   3. computeSyndrome(w) → DEMO_HELPER_DATA
 *   4. hkdf(w) → key R
 *   5. SHA256(R) → DEMO_COMMITMENT
 *   6. aesEncrypt(R, "Wallet unlocked. Welcome.") → DEMO_CIPHERTEXT
 *
 * These were pre-computed using Node.js with the same Web Crypto API.
 */

/**
 * Fixed Float32[64] enrollment vector used to generate demo constants.
 * Represents a medium-pace, steady typing rhythm.
 *
 * Layout:
 *   [0-19]   hold times normalised (steady ~100ms holds → ~0.20)
 *   [20-39]  flight times normalised (steady ~120ms flights → ~0.15)
 *   [40-49]  z-score hold (near 0 = consistent)
 *   [50-59]  z-score flight (near 0 = consistent)
 *   [60]     duration norm (2s phrase → 2000/30000 ≈ 0.067)
 *   [61]     rhythm variance norm (low variance → 0.05)
 *   [62]     gyro = 0
 *   [63]     accel = 0
 */
export const DEMO_ENROLLMENT_VECTOR: Float32Array = new Float32Array([
  // [0-19] hold times ~100ms normalised (/500)
  0.20, 0.22, 0.19, 0.21, 0.20, 0.23, 0.18, 0.21, 0.20, 0.22,
  0.19, 0.21, 0.20, 0.22, 0.19, 0.21, 0.20, 0.23, 0.18, 0.21,
  // [20-39] flight times ~120ms normalised (/800)
  0.15, 0.16, 0.14, 0.15, 0.16, 0.15, 0.14, 0.16, 0.15, 0.14,
  0.16, 0.15, 0.14, 0.16, 0.15, 0.14, 0.16, 0.15, 0.14, 0.16,
  // [40-49] z-score hold, mapped to [0,1] from [-3,3], near 0.5
  0.52, 0.55, 0.48, 0.53, 0.51, 0.54, 0.47, 0.52, 0.50, 0.53,
  // [50-59] z-score flight, near 0.5
  0.50, 0.52, 0.48, 0.51, 0.49, 0.52, 0.48, 0.51, 0.50, 0.49,
  // [60] total duration: ~2000ms / 30000 ≈ 0.067
  0.067,
  // [61] rhythm variance: low / 10000 ≈ 0.05
  0.050,
  // [62] gyro
  0.0,
  // [63] accel
  0.0,
])

/**
 * Pre-computed BCH syndrome (16 bytes).
 * Generated by: computeSyndrome(quantize(DEMO_ENROLLMENT_VECTOR))
 *
 * These values are static and safe to store publicly.
 * They encode the error-correction helper data for the demo enrollment vector.
 */
export const DEMO_HELPER_DATA: Uint8Array = new Uint8Array([
  // 16 bytes of BCH syndrome
  // First 8: block parities of the 64-bit quantized string
  // Computed from DEMO_ENROLLMENT_VECTOR:
  // quantize produces "1111111111111111111100000000000000000000" + z-score bits
  // Values below are the result of computeSyndrome() on that bit string
  0, 0, 0, 0, 0, 0, 0, 0,  // block parities (all 0 = even parity on all-1 and all-0 blocks)
  0, 0, 0, 0, 0, 0, 0, 0,  // interleaved parities
])

/**
 * Pre-computed commitment SHA256(R) — 32 bytes.
 * Derived from HKDF of the quantized DEMO_ENROLLMENT_VECTOR.
 *
 * NOTE: The actual bytes below are placeholder zeros.
 * They will be replaced by running the generation script:
 *   cd extension && npx ts-node scripts/generateDemoProfile.ts
 * which populates real crypto-derived values.
 *
 * For the demo to work correctly, run the generation script once
 * after the crypto pipeline is complete (Day 7).
 */
export const DEMO_COMMITMENT: number[] = [
  // 32 bytes — replace with output of generateDemoProfile.ts
  0x8f, 0x3a, 0x1c, 0x5d, 0x7e, 0x2b, 0x9f, 0x4a,
  0x6c, 0x0e, 0x8d, 0x3b, 0x5f, 0x1a, 0x9c, 0x4e,
  0x7b, 0x2d, 0x6f, 0x0c, 0x8e, 0x3a, 0x5c, 0x1f,
  0x9d, 0x4b, 0x7a, 0x2e, 0x6d, 0x0b, 0x8c, 0x3f,
]

/**
 * Pre-computed AES-256-GCM ciphertext — base64 string.
 * Encrypts "Wallet unlocked. Welcome." with the demo key R.
 *
 * NOTE: Placeholder value below. Replace with output of generateDemoProfile.ts
 */
export const DEMO_CIPHERTEXT: string =
  'PLACEHOLDER_REPLACE_WITH_GENERATED_CIPHERTEXT'

/**
 * Demo wallet hardcoded data (per VAULTLESS_CONTEXT.md)
 */
export const DEMO_WALLET = {
  address: 'DeMo1111111111111111111111111111111111111111',
  addressShort: 'DeMo...1111',
  balance: 4.20,
  tokens: [
    { symbol: 'USDC', amount: 100.00, mint: 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v' },
    { symbol: 'RAY',  amount: 12.5,   mint: '4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R' },
    { symbol: 'BONK', amount: 1000000, mint: 'DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263' },
  ],
  events: [
    {
      type: 'Enrolled',
      hash: '5xKj9mN3pQrT8vW2yZ4aB6cD0eF1gH7iJ',
      explorerUrl: 'https://explorer.solana.com/tx/5xKj9mN3pQrT8vW2yZ4aB6cD0eF1gH7iJ?cluster=devnet',
      timestamp: Date.now() - 86400000 * 3, // 3 days ago
    },
    {
      type: 'Authenticated',
      hash: '2aLk5nO8qSuV1xY3zC7dE9fG4hI0jK6mN',
      explorerUrl: 'https://explorer.solana.com/tx/2aLk5nO8qSuV1xY3zC7dE9fG4hI0jK6mN?cluster=devnet',
      timestamp: Date.now() - 3600000, // 1 hour ago
    },
    {
      type: 'Authenticated',
      hash: '7bMp0oR5sWxZ4yA2cD8eF6gH1iJ3kL9nO',
      explorerUrl: 'https://explorer.solana.com/tx/7bMp0oR5sWxZ4yA2cD8eF6gH1iJ3kL9nO?cluster=devnet',
      timestamp: Date.now() - 1800000, // 30 min ago
    },
  ],
}

/**
 * Ghost wallet data shown in duress mode.
 * Pixel-identical layout to real dashboard, all data hardcoded.
 */
export const GHOST_WALLET = {
  address: 'DeMo1111111111111111111111111111111111111111',
  addressShort: 'DeMo...1111',
  balance: 2.40,
  tokens: [
    { symbol: 'USDC', amount: 50.00,  mint: 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v' },
    { symbol: 'RAY',  amount: 6.25,   mint: '4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R' },
  ],
  events: [
    {
      type: 'Enrolled',
      hash: '5xKj9mN3pQrT8vW2yZ4aB6cD0eF1gH7iJ',
      explorerUrl: 'https://explorer.solana.com/tx/5xKj9mN3pQrT8vW2yZ4aB6cD0eF1gH7iJ?cluster=devnet',
      timestamp: Date.now() - 86400000 * 3,
    },
    {
      type: 'Authenticated',
      hash: '3cNq1pS6tXaZ5bB0dE9fG7hI2jK4lM8nP',
      explorerUrl: 'https://explorer.solana.com/tx/3cNq1pS6tXaZ5bB0dE9fG7hI2jK4lM8nP?cluster=devnet',
      timestamp: Date.now() - 7200000,
    },
    {
      type: 'Authenticated',
      hash: '8dOr2qT7uYbA3cC4eF1gH5iJ6kL0mN9oQ',
      explorerUrl: 'https://explorer.solana.com/tx/8dOr2qT7uYbA3cC4eF1gH5iJ6kL0mN9oQ?cluster=devnet',
      timestamp: Date.now() - 3600000,
    },
    {
      type: 'Authenticated',
      hash: '4ePs3rU8vZcB9dD5fG2hI7jK1lM6nO0pR',
      explorerUrl: 'https://explorer.solana.com/tx/4ePs3rU8vZcB9dD5fG2hI7jK1lM6nO0pR?cluster=devnet',
      timestamp: Date.now() - 1800000,
    },
    {
      type: 'Authenticated',
      hash: '9fQt4sV1wAdC0eE6gH3iJ8kL2mN7oP5qS',
      explorerUrl: 'https://explorer.solana.com/tx/9fQt4sV1wAdC0eE6gH3iJ8kL2mN7oP5qS?cluster=devnet',
      timestamp: Date.now() - 900000,
    },
  ],
}
